site_name: RunningMate Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: amber
nav:
  - Home: index.md
  - App :
      - Main Screen: ui/main-window.md
      - Detail View: ui/detail-window.md
      - User Settings: ui/user-settings.md
  - Metrics :
      - Heart Rate Zones: metrics/heart-rate-zones.md
      - Pace: metrics/pace.md
      - Trainings Effect: metrics/trainings-effect.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math