name: CI - Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest --cov=. --cov-report=xml || echo "Tests failed, but will not fail pipeline on non-main branches"

      - name: Fail if tests fail (only on main or PR)
        if: failure() && (github.ref == 'refs/heads/main' || github.event_name == 'pull_request')
        run: exit 1