name: CI - Run Tests & Linting & Deploy MkDocs

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Run Linting & Formatting Checks (Ruff, Black, isort)
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          ruff check . --output-format=github
          black --check .
          isort --check-only .

      - name: Run Tests
        run: |
          pytest --cov=. --cov-report=xml || echo "Tests failed, but will not fail pipeline on non-main branches"

      - name: Fail if tests or linting fail (only on main or PR)
        if: failure() && (github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'main')
        run: exit 1

  deploy:
    name: Deploy MkDocs
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and Dependencies
        run: |
          pip install mkdocs mkdocs-material
          pip install https://github.com/mitya57/python-markdown-math/archive/master.zip

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy MkDocs to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages